# Generated by Django 5.0.6 on 2024-06-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
