# Generated by Django 5.0.6 on 2024-05-18 23:08

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_status', models.IntegerField(choices=[(0, 'Eliminado'), (1, 'Habilitado'), (2, 'Deshabilitado')], default=1, verbose_name='Estado')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('elimination_date', models.DateTimeField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='Código')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=500, null=True, verbose_name='Marca')),
                ('hardware_code', models.CharField(blank=True, max_length=500, null=True, verbose_name='Codigo Ferretería')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
